spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zy?characterEncoding=utf8&useOldAliasMetadataBehavior=true&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: ENC(k5IohO2XLuAhwRbqdoQXc1Ab09Of3yQF)
    password: ENC(k5IohO2XLuAhwRbqdoQXc1Ab09Of3yQF)
  #redis配置
  redis:
    #单机模式，url解析有bug，改成host和port解析
    #url: "redis://127.0.0.1:6379"
    password: ENC(TUjeJQU0g3pGZqbYlDw8mHilUTdV+M1XlYZGeBc7WYg=)
    timeout: 100000ms
    host: 127.0.0.1
    port: 6379
#    #哨兵模式
#    sentinel:
#      #主节点名称
#      master: mymaster
#      #所有节点列表
#      nodes: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381
#      #主从节点互相认证的密码，保持一致
#      password: ENC(TUjeJQU0g3pGZqbYlDw8mHilUTdV+M1XlYZGeBc7WYg=)
#    #集群模式
#    cluster:
#      #所有节点列表
#      nodes: localhost:6379
#      #最大重定向其它节点的次数，防止死循环
#      max-redirects: 3

redisson:
  #是否手动注册redisson bean
  enable: true
  #redisson的模式（single/sentinel/cluster）
  mode: single
  #single模式下的url
  url: "redis://127.0.0.1:6379"

#/swagger-ui.html
swagger:
  enabled: true